apiVersion: apps/v1
kind: Deployment
metadata:
  name: uppgift2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uppgift2
  template:
    metadata:
      labels:
        app: uppgift2
    spec:
      containers:
      - name: uppgift2
        image: uppgift2
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
